### ISSUE TITLE
Enable GitHub actions to publish to GitHub Pages

### ISSUE THREAD

**Issue by jtpio** [DerThorsten/sample-python-repl#3]
Looks like the workflow failed to publish to GitHub Pages: https://github.com/emscripten-forge/sample-python-repl/actions/runs/4795486188/jobs/8530117589

@DerThorsten I don't have the rights on this repo to enable the GitHub Pages so would you mind doing it?

You can find it under the Settings. Here is an example with another repo:

![image](https://user-images.githubusercontent.com/591645/234230619-956cfc7e-a774-4c32-8dd3-cfe6d0c8ca23.png)

Thanks!

**Comment by DerThorsten** [comment]
done! Thanks!

**Comment by jtpio** [comment]
Cool! Now it should be possible to trigger a new build by restarting the workflow.
