### ISSUE TITLE
Add link to the GitHub Pages deployment

### ISSUE THREAD

**Issue by jtpio** [DerThorsten/sample-python-repl#4]
It would be nice to add the link to the GitHub Pages deployment as part of the repo home page so it's easier to try it out: https://emscripten-forge.github.io/sample-python-repl/

![image](https://user-images.githubusercontent.com/591645/234262403-1c7f23d6-089c-441d-9844-342b9c6c5c9e.png)

cc @DerThorsten since I don't have the rights to do it

**Comment by DerThorsten** [comment]
fyi, added you to emscripten-forge

**Comment by DerThorsten** [comment]
done! and thanks!

**Comment by jtpio** [comment]
Nice, thanks!
